### ISSUE TITLE
Extract pre-built reports into separate class

### ISSUE THREAD

**Issue by Plytas** [gtmassey/Analytics#11]
I think it would help us keep the classes cleaner. Obviously it should not affect user experience, so the call could stay the same `Analytics::getTopEvents();`, but the method itself could reside in a separate class. We could either do some magic `__call()` or put them in a trait.

**Comment by gtmassey** [comment]
Working on this in the branch [extractReportMethods](https://github.com/gtmassey/Analytics/tree/extractReportMethods)
