### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by vpuentem** [gtmassey/Analytics#55]
I'm getting conflicts when upgrading to laravel 11 due to this package, is it planned to add laravel 11 support? 

Thanks in advance and for developing this package!

**Comment by Plytas** [comment]
Hey @vpuentem. I've opened a PR that adds Laravel 11 support. Please test it out by running `composer require gtmassey/laravel-analytics:dev-laravel-11-support`.

**Comment by Plytas** [comment]
Just a heads up, it might be blocked by https://github.com/gtmassey/period/pull/2. I've pinged @gtmassey to update it.

**Comment by gtmassey** [comment]
On the current pr #56, I am unable to get the tests to pass right now, and it seems to be an issue with the credentials. It's still open for anyone to take a look at. At some point we need to look into upgrading the Google Analytics API package as well, as they're on v.0.20 something now, and we are using v0.9. @Plytas if you have any idea why the tests are failing let me know. I'm still on Discord.

**Comment by gtmassey** [comment]
Closed by PR #56
