### ISSUE TITLE
Sort out codestyle

### ISSUE THREAD

**Issue by Plytas** [gtmassey/Analytics#7]
We should consider unifying code style through some automation.

Possible solutions:
* [Laravel Pint](https://laravel.com/docs/9.x/pint)
* [Style CI](https://styleci.io/)

**Comment by gtmassey** [comment]
Laravel Pint has been applied to the codebase, and the command `composer pint` has been added to the `scripts` as well. Now when a PR is made, it will check against Laravel Pint, so I would recommend that before pushing or making  a PR, you run `composer pint` on your local env and you shouldn't run into any issues.
